# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/user/owl-chr/owlChrpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/user/owl-chr/owlChrpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/cmake/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/owl-chr/owlChrpp/CMakeFiles /home/user/owl-chr/owlChrpp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/owl-chr/owlChrpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/user/owl-chr/owlChrpp/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named generate_owl_cpp

# Build rule for target.
generate_owl_cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 generate_owl_cpp
.PHONY : generate_owl_cpp

# fast build rule for target.
generate_owl_cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generate_owl_cpp.dir/build.make CMakeFiles/generate_owl_cpp.dir/build
.PHONY : generate_owl_cpp/fast

#=============================================================================
# Target rules for targets named ParserProject

# Build rule for target.
ParserProject: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ParserProject
.PHONY : ParserProject

# fast build rule for target.
ParserProject/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParserProject.dir/build.make CMakeFiles/ParserProject.dir/build
.PHONY : ParserProject/fast

#=============================================================================
# Target rules for targets named cowl-readers

# Build rule for target.
cowl-readers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cowl-readers
.PHONY : cowl-readers

# fast build rule for target.
cowl-readers/fast:
	$(MAKE) $(MAKESILENT) -f lib/cowl/CMakeFiles/cowl-readers.dir/build.make lib/cowl/CMakeFiles/cowl-readers.dir/build
.PHONY : cowl-readers/fast

#=============================================================================
# Target rules for targets named cowl-writers

# Build rule for target.
cowl-writers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cowl-writers
.PHONY : cowl-writers

# fast build rule for target.
cowl-writers/fast:
	$(MAKE) $(MAKESILENT) -f lib/cowl/CMakeFiles/cowl-writers.dir/build.make lib/cowl/CMakeFiles/cowl-writers.dir/build
.PHONY : cowl-writers/fast

#=============================================================================
# Target rules for targets named cowl

# Build rule for target.
cowl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cowl
.PHONY : cowl

# fast build rule for target.
cowl/fast:
	$(MAKE) $(MAKESILENT) -f lib/cowl/CMakeFiles/cowl.dir/build.make lib/cowl/CMakeFiles/cowl.dir/build
.PHONY : cowl/fast

#=============================================================================
# Target rules for targets named ulib

# Build rule for target.
ulib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ulib
.PHONY : ulib

# fast build rule for target.
ulib/fast:
	$(MAKE) $(MAKESILENT) -f lib/cowl/lib/ulib/CMakeFiles/ulib.dir/build.make lib/cowl/lib/ulib/CMakeFiles/ulib.dir/build
.PHONY : ulib/fast

#=============================================================================
# Target rules for targets named cowl-functional-reader

# Build rule for target.
cowl-functional-reader: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cowl-functional-reader
.PHONY : cowl-functional-reader

# fast build rule for target.
cowl-functional-reader/fast:
	$(MAKE) $(MAKESILENT) -f lib/cowl/src/formats/functional/reader/CMakeFiles/cowl-functional-reader.dir/build.make lib/cowl/src/formats/functional/reader/CMakeFiles/cowl-functional-reader.dir/build
.PHONY : cowl-functional-reader/fast

owl.o: owl.cpp.o
.PHONY : owl.o

# target to build an object file
owl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParserProject.dir/build.make CMakeFiles/ParserProject.dir/owl.cpp.o
.PHONY : owl.cpp.o

owl.i: owl.cpp.i
.PHONY : owl.i

# target to preprocess a source file
owl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParserProject.dir/build.make CMakeFiles/ParserProject.dir/owl.cpp.i
.PHONY : owl.cpp.i

owl.s: owl.cpp.s
.PHONY : owl.s

# target to generate assembly for a file
owl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParserProject.dir/build.make CMakeFiles/ParserProject.dir/owl.cpp.s
.PHONY : owl.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... cowl-functional-reader"
	@echo "... cowl-readers"
	@echo "... cowl-writers"
	@echo "... generate_owl_cpp"
	@echo "... ParserProject"
	@echo "... cowl"
	@echo "... ulib"
	@echo "... owl.o"
	@echo "... owl.i"
	@echo "... owl.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/user/owl-chr/owlChrpp/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

